language: python
python:
- '2.7'
virtualenv:
  system_site_packages: true
services:
- postgresql
env:
  global:
  - TKP_DBNAME=testdb
  - TKP_DBENGINE=postgresql
  - TKP_DBUSER=postgres
  - TKP_DBPASS=postgres
  - TKP_TESTPATH=${TRAVIS_BUILD_DIR}/tests/data
notifications:
  hipchat:
    rooms:
      secure: ZhAQEKkc9bwt4O9TyL4Bdpic/5mme1A9QnFt38BlotvCPkIp19EhH/Qh7M76eCPrAIOngfO7GhnFj7SgjOQ7u5XxohC3Fak9MaUhBeew0GDYEcTq+7WDVQ3FVjyOcWOJMi5nBCKVK/SqOIdmCfBS+waBog7be2VQXcfcej8g2+E=
before_install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository -y ppa:radio-astro/main
  - sudo apt-get update -q
  - sudo apt-get install -qy casacore-data libcasacore2-dev python-numpy python-scipy libboost-python-dev libcfitsio3-dev wcslib-dev
  - psql -c "ALTER ROLE postgres WITH PASSWORD 'postgres';" -U postgres
  - psql -c "create database testdb;" -U postgres
  - git submodule init
  - git submodule update
install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install --upgrade pip
  - pip install .
  - pip install nose
  - pip freeze
script:
  - cd /tmp
  - "${TRAVIS_BUILD_DIR}/tkp/bin/trap-manage.py initproject pipeline"
  - cd pipeline
  - "${TRAVIS_BUILD_DIR}/tkp/bin/trap-manage.py initdb -y"
  - cd ${TRAVIS_BUILD_DIR}/tests
  - TKP_DBUSER=postgres TKP_DBPASSWORD= nosetests -sv
